export const Redshift = {
  order:
    "(_id varchar(500)" +
    ", " +
    "client_uuid varchar(500)" +
    ", " +
    "client_name varchar(100)" +
    ", " +
    "store_uuid varchar(500)" +
    ", " +
    "store_code varchar(35)" +
    ", " +
    "store_type varchar(35)" +
    ", " +
    "store_name varchar(500)" +
    ", " +
    "platform varchar(35)" +
    ", " +
    "business_date varchar(50)" +
    ", " +
    "business_year varchar(50)" +
    ", " +
    "business_month varchar(50)" +
    ", " +
    "business_quater varchar(50)" +
    ", " +
    "business_hour varchar(50)" +
    ", " +
    "order_code varchar(500)" +
    ", " +
    "order_number varchar(500)" +
    ", " +
    "order_date varchar(500)" +
    ", " +
    "order_time varchar(500)" +
    ", " +
    "promise_date varchar(35)" +
    ", " +
    "promise_time varchar(35)" +
    ", " +
    "channel varchar(35)" +
    ", " +
    "channel_code varchar(35)" +
    ", " +
    "customer_identifier varchar(35)" +
    ", " +
    "order_type varchar(35)" +
    ", " +
    "order_device varchar(35)" +
    ", " +
    "advance_order varchar(35)" +
    ", " +
    "is_oc varchar(35)" +
    ", " +
    "transaction_value_with_tax int8" +
    ", " +
    "delivery_fee int8" +
    ", " +
    "tax int8" +
    ", " +
    "transaction_value_without_tax_delivery_fee int8" +
    ", " +
    "product_total_cost int8" +
    ", " +
    "sos_kpi_met varchar(1)" +
    ", " +
    "hot_fresh_met varchar(1)" +
    ", " +
    "delivery_lat varchar(100)" +
    ", " +
    "delivery_long varchar(100)" +
    ", " +
    "delivery_zone_id varchar(100)" +
    ", " +
    "delivery_zone_name varchar(100)" +
    ", " +
    "collection_time TIMESTAMP" +
    ", " +
    "kds_time TIMESTAMP" +
    ", " +
    "bake_time TIMESTAMP" +
    ", " +
    "created_date TIMESTAMP" +
    "); ",
  order_detail:
    "(_id varchar(500)" +
    ", " +
    "client_uuid varchar(100)" +
    ", " +
    "client_name varchar(100)" +
    ", " +
    "store_uuid varchar(500)" +
    ", " +
    "store_code varchar(35)" +
    ", " +
    "store_name varchar(100)" +
    ", " +
    "business_date varchar(50)" +
    ", " +
    "business_year varchar(50)" +
    ", " +
    "business_month varchar(50)" +
    ", " +
    "business_quater varchar(50)" +
    ", " +
    "business_hour varchar(50)" +
    ", " +
    "order_code varchar(100)" +
    ", " +
    "order_number varchar(100)" +
    ", " +
    "order_detail_uuid varchar(100)" +
    ", " +
    "is_combo varchar(10)" +
    ", " +
    "product_category_code varchar(100)" +
    ", " +
    "product_category_name varchar(100)" +
    ", " +
    "product_code varchar(100)" +
    ", " +
    "product_name varchar(100)" +
    ", " +
    "option_group_code varchar(100)" +
    ", " +
    "option_group_name varchar(100)" +
    ", " +
    "option_code varchar(100)" +
    ", " +
    "option_name varchar(100)" +
    ", " +
    "product_inventory_code varchar(100)" +
    ", " +
    "product_inventory_name varchar(100)" +
    ", " +
    "quantity varchar(10)" +
    ", " +
    "sku varchar(100)" +
    ", " +
    "order_time varchar(100)" +
    ", " +
    "collection_time TIMESTAMP" +
    ", " +
    "created_date TIMESTAMP" +
    "); ",
  order_log_time:
    "(_id varchar(500)" +
    ", " +
    "client_uuid varchar(100)" +
    ", " +
    "client_name varchar(100)" +
    ", " +
    "store_uuid varchar(500)" +
    ", " +
    "store_code varchar(35)" +
    ", " +
    "store_name varchar(100)" +
    ", " +
    "business_date varchar(50)" +
    ", " +
    "business_year varchar(50)" +
    ", " +
    "business_month varchar(50)" +
    ", " +
    "business_quater varchar(50)" +
    ", " +
    "business_hour varchar(50)" +
    ", " +
    "order_code varchar(100)" +
    ", " +
    "order_number varchar(100)" +
    ", " +
    "promise_datetime TIMESTAMP" +
    ", " +
    "expected_start_make_time TIMESTAMP" +
    ", " +
    "expected_make_time TIMESTAMP" +
    ", " +
    "actual_make_time TIMESTAMP" +
    ", " +
    "show_popup_make_time TIMESTAMP" +
    ", " +
    "clickok_popup_make_time TIMESTAMP" +
    ", " +
    "actual_cut_time TIMESTAMP" +
    ", " +
    "delivery_assign_time TIMESTAMP" +
    ", " +
    "delivery_start_time TIMESTAMP" +
    ", " +
    "order_completion_time TIMESTAMP" +
    ", " +
    "customer_receive_time TIMESTAMP" +
    ", " +
    "in_store_time TIMESTAMP" +
    ", " +
    "canceled_time TIMESTAMP" +
    "); ",
};
